export const projects = [
  {
    headline: "DASHBOARD REGIDENT KORLANTAS",
    timeline: "2022",
    background: "../assets/img/projects/DRK/background.jpeg",
    logo: "/assets/img/projects/DRK/Logo.png",
    src: "/assets/img/projects/DRK/DRK.jpg",
    responsibilities: "Full Stack Developer",
    description: "A Web dashboard for vehicle data visualization",
    jobDesc:
      "I developed a web application integrated with the ERI (Electronic Registration Records) system, which also visualizes data and Docker deployment",
    techStack: ["Vue", "Node.js", "PostgreSQL", "Apache Superset"],
    siteAvailability: false,
  },
  {
    headline: "SCM",
    timeline: "2022",
    background: "/assets/img/projects/SCM/background.jpg",
    logo: "/assets/img/projects/SCM/Logo.png",
    src: "/assets/img/projects/SCM/SCM.jpg",
    responsibilities: "Frontend Developer",
    description: "Web for digital forensic evidence management",
    jobDesc: "I developed a web application designed to provide a customized information view, adjusting the content based on the user's role",
    techStack: ["Vue", "Vuetify", "Vite"],
    siteAvailability: false,
  },
  {
    headline: "IRSJAM",
    timeline: "2022",
    background: "/assets/img/projects/IRSJAM/background.jpg",
    logo: "/assets/img/projects/IRSJAM/Logo.png",
    src: "/assets/img/projects/IRSJAM/IRSJAM.jpg",
    responsibilities: "Frontend Developer",
    description: "A platform for communication and coordination among member hospitals",
    jobDesc: "I was responsible for developing responsive web redesigns and managing CMS content.",
    techStack: ["CodeIgniter", "Wordpress", "GraphQL"],
    siteAvailability: true,
    site: "https://irsjam.or.id/",
  },
  {
    headline: "VMS",
    timeline: "2022",
    background: "/assets/img/projects/VMS/background.jpg",
    logo: "/assets/img/projects/VMS/Logo.png",
    src: "/assets/img/projects/VMS/VMS.jpg",
    src2: "/assets/img/projects/VMS/VMS-Mobile.png",
    responsibilities: "Full Stack Developer & Mobile Developer",
    description: "Web for visitor check-in and reservations",
    jobDesc: "I have contributed to developing web and mobile applications and configuring CI/CD pipelines on GitLab",
    techStack: ["Vue", "Vitest", "Flutter", "FastAPI", "PostgreSQL"],
    siteAvailability: false,
  },
  {
    headline: "Medtronic",
    timeline: "2022",
    background: "/assets/img/projects/Medtronic/background.jpg",
    logo: "/assets/img/projects/Medtronic/Logo.png",
    src: "/assets/img/projects/Medtronic/Medtronic.jpg",
    responsibilities: "Frontend Developer",
    description: "Web for visitor check-in and reservations",
    jobDesc: "I was involved in developing a web application that provides real-time notification features",
    techStack: ["Angular", "Socket.IO", "Jest"],
    siteAvailability: false,
  },
]
